from .beta import BETA
from .correl import CORREL
from .linearreg import LINEARREG
from .linearreg_angle import LINEARREG_ANGLE
from .linearreg_intercept import LINEARREG_INTERCEPT
from .linearreg_slope import LINEARREG_SLOPE
from .stddev import STDDEV
from .tsf import TSF
from .var import VAR
