# Auto-generated by factor_generator using polats ta-lib.py
import polars as pl
import polars_talib as plta

from vnpy.factor.template import FactorTemplate
from vnpy.factor.memory import FactorMemory

DEFAULT_DATETIME_COL = "datetime"


class MAVP(FactorTemplate):
    """
    Calculates the MAVP indicator.
    """

    author = "Auto-Generated by FactorGenerator"
    factor_name = "MAVP"

    def __init__(self, setting: dict | None = None, vt_symbols: list[str] | None = None, **kwargs):
        """
        Initializes the MAVP.
        Required parameters: periods, minperiod, maxperiod, matype
        """
        super().__init__(setting, **kwargs)
        self.vt_symbols: list[str] = vt_symbols if vt_symbols else []

        # --- Parameter Validation and Assignment ---
        if not hasattr(self.params, "periods"): raise ValueError(f"{self.factor_key} requires a 'periods' parameter.")
        try: self.periods = float(self.params.periods)
        except (ValueError, TypeError): self.periods = int(self.params.periods)
        if not hasattr(self.params, "minperiod"): raise ValueError(f"{self.factor_key} requires a 'minperiod' parameter.")
        try: self.minperiod = float(self.params.minperiod)
        except (ValueError, TypeError): self.minperiod = int(self.params.minperiod)
        if not hasattr(self.params, "maxperiod"): raise ValueError(f"{self.factor_key} requires a 'maxperiod' parameter.")
        try: self.maxperiod = float(self.params.maxperiod)
        except (ValueError, TypeError): self.maxperiod = int(self.params.maxperiod)
        if not hasattr(self.params, "matype"): raise ValueError(f"{self.factor_key} requires a 'matype' parameter.")
        try: self.matype = float(self.params.matype)
        except (ValueError, TypeError): self.matype = int(self.params.matype)

    def calculate(self, input_data: dict[str, pl.DataFrame], memory: FactorMemory) -> pl.DataFrame:
        """Calculates the indicator by iterating through symbols and executing eagerly."""
        # --- Input Data Validation ---
        if input_data.get("close") is None: return pl.DataFrame(data={}, schema=self.get_output_schema())

        # --- Eager Calculation Loop ---
        df_base = input_data.get("close") or next(iter(input_data.values()))
        symbol_columns = [col for col in df_base.columns if col != DEFAULT_DATETIME_COL]
        if self.vt_symbols:
            symbol_columns = [col for col in symbol_columns if col in self.vt_symbols]

        if not symbol_columns:
            return pl.DataFrame(data={}, schema=self.get_output_schema())

        kwargs = { "periods": self.periods, "minperiod": self.minperiod, "maxperiod": self.maxperiod, "matype": self.matype }
        output_series_list = []

        for symbol in symbol_columns:
            # Build the keyword arguments by extracting the pl.Series for this symbol
            # E.g., {'high': input_data['high'][symbol], 'low': input_data['low'][symbol]}
            symbol_inputs = { "real": input_data["close"][symbol] }

            # Execute the calculation immediately for this single symbol
            result_series_or_struct = plta.mavp(**symbol_inputs, **kwargs)

            # If this is a component of a multi-output function, extract the field.
            if "":
                final_series = result_series_or_struct.struct.field("")
            else:
                final_series = result_series_or_struct

            output_series_list.append(final_series.alias(symbol))

        # Combine the datetime column with the list of calculated series
        datetime_col_df = df_base.select(pl.col(DEFAULT_DATETIME_COL))
        result_df = datetime_col_df.with_columns(output_series_list)
        return result_df

