# Auto-generated by factor_generator.py using polars-talib
import polars as pl
import polars_talib as plta
from typing import Dict, List

from vnpy.factor.template import FactorTemplate
from vnpy.factor.memory import FactorMemory

DEFAULT_DATETIME_COL = "datetime"


class ROCR(FactorTemplate):
    """
    Calculates the ROCR indicator.
    """

    author = "Auto-Generated by FactorGenerator"
    factor_name = "ROCR"

    def __init__(self, setting: dict | None = None, **kwargs):
        """
        Initializes the ROCR.
        Required parameters: timeperiod
        """
        super().__init__(setting, **kwargs)

        # --- Parameter Validation and Assignment ---
        if not hasattr(self.params, "timeperiod"): raise ValueError(f"{self.factor_key} requires a 'timeperiod' parameter.")
        try: self.timeperiod = int(self.params.timeperiod)
        except (ValueError, TypeError): self.timeperiod = float(self.params.timeperiod)

    def calculate(self, input_data: dict[str, pl.DataFrame], memory: FactorMemory) -> pl.DataFrame:
        """Calculates the indicator using a temporary DataFrame and expression API for each symbol."""
        # --- Input Data Validation ---
        if input_data["close"].is_empty(): return pl.DataFrame(data={}, schema=self.get_output_schema())

        # --- Eager Calculation Loop ---
        df_base = input_data.get("close")
        symbol_columns = [col for col in df_base.columns if col != DEFAULT_DATETIME_COL]
        if self.vt_symbols:
            symbol_columns = [col for col in symbol_columns if col in self.vt_symbols]

        if not symbol_columns:
            return pl.DataFrame(data={}, schema=self.get_output_schema())

        kwargs = { "timeperiod": self.timeperiod }
        output_series_list = []

        for symbol in symbol_columns:
            # 1. Create a temporary DataFrame with this symbol's required inputs
            temp_df_inputs = { "real": input_data["close"][symbol] }
            input_df = pl.DataFrame(temp_df_inputs)

            # 2. Define the calculation expression using pl.col()
            calc_expression = plta.rocr(real=pl.col("real"), **kwargs).alias("result")

            # 3. Execute the expression on the temporary DataFrame
            result_df_with_indicator = input_df.with_columns(calc_expression)

            result_series_or_struct = result_df_with_indicator.get_column("result")

            # 4. Handle multi-output indicators if necessary using index access
            if False:
                final_series = result_series_or_struct.struct[None]
            else:
                final_series = result_series_or_struct

            output_series_list.append(final_series.alias(symbol))

        # Combine the datetime column with the list of calculated series
        datetime_col_df = df_base.select(pl.col(DEFAULT_DATETIME_COL))
        result_df = datetime_col_df.with_columns(output_series_list)
        return result_df

