# Auto-generated by factor_generator using polats ta-lib.py
import polars as pl
import polars_talib as plta

from vnpy.factor.template import FactorTemplate
from vnpy.factor.memory import FactorMemory

DEFAULT_DATETIME_COL = "datetime"


class STOCH_SLOWD(FactorTemplate):
    """
    Calculates the STOCH_SLOWD indicator.
    """

    author = "Auto-Generated by FactorGenerator"
    factor_name = "STOCH_SLOWD"

    def __init__(self, setting: dict | None = None, vt_symbols: list[str] | None = None, **kwargs):
        """
        Initializes the STOCH_SLOWD.
        Required parameters: fastk_period, slowk_period, slowk_matype, slowd_period, slowd_matype
        """
        super().__init__(setting, **kwargs)
        self.vt_symbols: list[str] = vt_symbols if vt_symbols else []

        # --- Parameter Validation and Assignment ---
        if not hasattr(self.params, "fastk_period"): raise ValueError(f"{self.factor_key} requires a 'fastk_period' parameter.")
        try: self.fastk_period = float(self.params.fastk_period)
        except (ValueError, TypeError): self.fastk_period = int(self.params.fastk_period)
        if not hasattr(self.params, "slowk_period"): raise ValueError(f"{self.factor_key} requires a 'slowk_period' parameter.")
        try: self.slowk_period = float(self.params.slowk_period)
        except (ValueError, TypeError): self.slowk_period = int(self.params.slowk_period)
        if not hasattr(self.params, "slowk_matype"): raise ValueError(f"{self.factor_key} requires a 'slowk_matype' parameter.")
        try: self.slowk_matype = float(self.params.slowk_matype)
        except (ValueError, TypeError): self.slowk_matype = int(self.params.slowk_matype)
        if not hasattr(self.params, "slowd_period"): raise ValueError(f"{self.factor_key} requires a 'slowd_period' parameter.")
        try: self.slowd_period = float(self.params.slowd_period)
        except (ValueError, TypeError): self.slowd_period = int(self.params.slowd_period)
        if not hasattr(self.params, "slowd_matype"): raise ValueError(f"{self.factor_key} requires a 'slowd_matype' parameter.")
        try: self.slowd_matype = float(self.params.slowd_matype)
        except (ValueError, TypeError): self.slowd_matype = int(self.params.slowd_matype)

    def calculate(self, input_data: dict[str, pl.DataFrame], memory: FactorMemory) -> pl.DataFrame:
        """Calculates the indicator by iterating through symbols and executing eagerly."""
        # --- Input Data Validation ---
        if input_data.get("high") is None: return pl.DataFrame(data={}, schema=self.get_output_schema())
        if input_data.get("close") is None: return pl.DataFrame(data={}, schema=self.get_output_schema())
        if input_data.get("low") is None: return pl.DataFrame(data={}, schema=self.get_output_schema())

        # --- Eager Calculation Loop ---
        df_base = input_data.get("close") or next(iter(input_data.values()))
        symbol_columns = [col for col in df_base.columns if col != DEFAULT_DATETIME_COL]
        if self.vt_symbols:
            symbol_columns = [col for col in symbol_columns if col in self.vt_symbols]

        if not symbol_columns:
            return pl.DataFrame(data={}, schema=self.get_output_schema())

        kwargs = { "fastk_period": self.fastk_period, "slowk_period": self.slowk_period, "slowk_matype": self.slowk_matype, "slowd_period": self.slowd_period, "slowd_matype": self.slowd_matype }
        output_series_list = []

        for symbol in symbol_columns:
            # Build the keyword arguments by extracting the pl.Series for this symbol
            # E.g., {'high': input_data['high'][symbol], 'low': input_data['low'][symbol]}
            symbol_inputs = { "high": input_data["high"][symbol], "low": input_data["low"][symbol], "close": input_data["close"][symbol] }

            # Execute the calculation immediately for this single symbol
            result_series_or_struct = plta.stoch(**symbol_inputs, **kwargs)

            # If this is a component of a multi-output function, extract the field.
            if "slowd":
                final_series = result_series_or_struct.struct.field("slowd")
            else:
                final_series = result_series_or_struct

            output_series_list.append(final_series.alias(symbol))

        # Combine the datetime column with the list of calculated series
        datetime_col_df = df_base.select(pl.col(DEFAULT_DATETIME_COL))
        result_df = datetime_col_df.with_columns(output_series_list)
        return result_df

