# Auto-generated by factor_generator using polats ta-lib.py
import polars as pl
import polars_talib as plta
from typing import Dict

from vnpy.factor.template import FactorTemplate
from vnpy.factor.memory import FactorMemory

DEFAULT_DATETIME_COL = "datetime"


class PLUS_DMFactor(FactorTemplate):
    """
    Calculates the PLUS_DM indicator.
    """

    author = "Auto-Generated by FactorGenerator"
    factor_name = "PLUS_DM"

    def __init__(self, setting: dict | None = None, vt_symbols: list[str] | None = None, **kwargs):
        """
        Initializes the PLUS_DMFactor.
        Required parameters: timeperiod
        """
        super().__init__(setting, **kwargs)
        self.vt_symbols: list[str] = vt_symbols if vt_symbols else []

        # --- Parameter Validation and Assignment ---
        if not hasattr(self.params, "timeperiod"): raise ValueError(f"{self.factor_key} requires a 'timeperiod' parameter.")
        try: self.timeperiod = float(self.params.timeperiod)
        except (ValueError, TypeError): self.timeperiod = int(self.params.timeperiod)


    def calculate(self, input_data: Dict[str, pl.DataFrame], memory: FactorMemory) -> pl.DataFrame:
        """Calculates the indicator and extracts the relevant component if necessary."""
        # --- Input Data Validation ---
        if input_data.get("low") is None or input_data["low"].is_empty(): return pl.DataFrame(data={}, schema=self.get_output_schema())
        if input_data.get("high") is None or input_data["high"].is_empty(): return pl.DataFrame(data={}, schema=self.get_output_schema())

        # --- Core Calculation ---
        df_base = input_data.get("close") or next(iter(input_data.values()))

        symbol_columns = [col for col in df_base.columns if col != DEFAULT_DATETIME_COL]
        if self.vt_symbols:
            symbol_columns = [col for col in symbol_columns if col in self.vt_symbols]

        if not symbol_columns:
            return pl.DataFrame(data={}, schema=self.get_output_schema())

        kwargs = { "timeperiod": self.timeperiod }
        expressions_to_run = []

        for symbol in symbol_columns:
            symbol_inputs = { "high": pl.col(symbol), "low": pl.col(symbol) }

            result_expr = plta.plus_dm(**symbol_inputs, **kwargs)

            # If this is a component of a multi-output function, extract the field.
            if "":
                result_expr = result_expr.struct.field("")

            expressions_to_run.append(result_expr.alias(symbol))

        # Join all necessary input dataframes for the calculation
        df_exec_base = df_base
        for col_name, df_wide in input_data.items():
            if col_name != "close" and col_name in {'low', 'high'}:
                if df_wide is not df_base:
                    df_exec_base = df_exec_base.join(df_wide.select(pl.all().exclude(DEFAULT_DATETIME_COL)), on=DEFAULT_DATETIME_COL, how="left")

        # Execute all expressions at once
        result_df = df_exec_base.select(pl.col(DEFAULT_DATETIME_COL), *expressions_to_run)
        return result_df

