# Auto-generated by factor_generator using polats ta-lib.py
import polars as pl
import polars_talib as plta
from typing import Dict

from vnpy.factor.template import FactorTemplate
from vnpy.factor.memory import FactorMemory

DEFAULT_DATETIME_COL = "datetime"


class MAVPFactor(FactorTemplate):
    """
    Calculates the MAVP indicator.
    """

    author = "Auto-Generated by FactorGenerator"
    factor_name = "MAVP"

    def __init__(self, setting: dict | None = None, vt_symbols: list[str] | None = None, **kwargs):
        """
        Initializes the MAVPFactor.
        Required parameters: periods, minperiod, maxperiod, matype
        """
        super().__init__(setting, **kwargs)
        self.vt_symbols: list[str] = vt_symbols if vt_symbols else []

        # --- Parameter Validation and Assignment ---
        if not hasattr(self.params, "periods"): raise ValueError(f"{self.factor_key} requires a 'periods' parameter.")
        try: self.periods = float(self.params.periods)
        except (ValueError, TypeError): self.periods = int(self.params.periods)
        if not hasattr(self.params, "minperiod"): raise ValueError(f"{self.factor_key} requires a 'minperiod' parameter.")
        try: self.minperiod = float(self.params.minperiod)
        except (ValueError, TypeError): self.minperiod = int(self.params.minperiod)
        if not hasattr(self.params, "maxperiod"): raise ValueError(f"{self.factor_key} requires a 'maxperiod' parameter.")
        try: self.maxperiod = float(self.params.maxperiod)
        except (ValueError, TypeError): self.maxperiod = int(self.params.maxperiod)
        if not hasattr(self.params, "matype"): raise ValueError(f"{self.factor_key} requires a 'matype' parameter.")
        try: self.matype = float(self.params.matype)
        except (ValueError, TypeError): self.matype = int(self.params.matype)


    def calculate(self, input_data: Dict[str, pl.DataFrame], memory: FactorMemory) -> pl.DataFrame:
        """Calculates the indicator and extracts the relevant component if necessary."""
        # --- Input Data Validation ---
        if input_data.get("close") is None or input_data["close"].is_empty(): return pl.DataFrame(data={}, schema=self.get_output_schema())

        # --- Core Calculation ---
        df_base = input_data.get("close") or next(iter(input_data.values()))

        symbol_columns = [col for col in df_base.columns if col != DEFAULT_DATETIME_COL]
        if self.vt_symbols:
            symbol_columns = [col for col in symbol_columns if col in self.vt_symbols]

        if not symbol_columns:
            return pl.DataFrame(data={}, schema=self.get_output_schema())

        kwargs = { "periods": self.periods, "minperiod": self.minperiod, "maxperiod": self.maxperiod, "matype": self.matype }
        expressions_to_run = []

        for symbol in symbol_columns:
            symbol_inputs = { "real": pl.col(symbol) }

            result_expr = plta.mavp(**symbol_inputs, **kwargs)

            # If this is a component of a multi-output function, extract the field.
            if "":
                result_expr = result_expr.struct.field("")

            expressions_to_run.append(result_expr.alias(symbol))

        # Join all necessary input dataframes for the calculation
        df_exec_base = df_base
        for col_name, df_wide in input_data.items():
            if col_name != "close" and col_name in {'close'}:
                if df_wide is not df_base:
                    df_exec_base = df_exec_base.join(df_wide.select(pl.all().exclude(DEFAULT_DATETIME_COL)), on=DEFAULT_DATETIME_COL, how="left")

        # Execute all expressions at once
        result_df = df_exec_base.select(pl.col(DEFAULT_DATETIME_COL), *expressions_to_run)
        return result_df

