# Auto-generated by factor_generator using polats ta-lib.py
import polars as pl
import polars_talib as plta
from typing import Dict

from vnpy.factor.template import FactorTemplate
from vnpy.factor.memory import FactorMemory

DEFAULT_DATETIME_COL = "datetime"


class REGISTER_PLUGINFactor(FactorTemplate):
    """
    Calculates the REGISTER_PLUGIN indicator.
    """

    author = "Auto-Generated by FactorGenerator"
    factor_name = "REGISTER_PLUGIN"

    def __init__(self, setting: dict | None = None, vt_symbols: list[str] | None = None, **kwargs):
        """
        Initializes the REGISTER_PLUGINFactor.
        Required parameters: kwargs, returns_scalar
        """
        super().__init__(setting, **kwargs)
        self.vt_symbols: list[str] = vt_symbols if vt_symbols else []

        # --- Parameter Validation and Assignment ---
        if not hasattr(self.params, "kwargs"): raise ValueError(f"{self.factor_key} requires a 'kwargs' parameter.")
        try: self.kwargs = float(self.params.kwargs)
        except (ValueError, TypeError): self.kwargs = int(self.params.kwargs)
        if not hasattr(self.params, "returns_scalar"): raise ValueError(f"{self.factor_key} requires a 'returns_scalar' parameter.")
        try: self.returns_scalar = float(self.params.returns_scalar)
        except (ValueError, TypeError): self.returns_scalar = int(self.params.returns_scalar)


    def calculate(self, input_data: Dict[str, pl.DataFrame], memory: FactorMemory) -> pl.DataFrame:
        """Calculates the indicator and extracts the relevant component if necessary."""
        # --- Input Data Validation ---


        # --- Core Calculation ---
        df_base = input_data.get("close") or next(iter(input_data.values()))

        symbol_columns = [col for col in df_base.columns if col != DEFAULT_DATETIME_COL]
        if self.vt_symbols:
            symbol_columns = [col for col in symbol_columns if col in self.vt_symbols]

        if not symbol_columns:
            return pl.DataFrame(data={}, schema=self.get_output_schema())

        kwargs = { "kwargs": self.kwargs, "returns_scalar": self.returns_scalar }
        expressions_to_run = []

        for symbol in symbol_columns:
            symbol_inputs = {  }

            result_expr = plta.register_plugin(**symbol_inputs, **kwargs)

            # If this is a component of a multi-output function, extract the field.
            if "":
                result_expr = result_expr.struct.field("")

            expressions_to_run.append(result_expr.alias(symbol))

        # Join all necessary input dataframes for the calculation
        df_exec_base = df_base
        for col_name, df_wide in input_data.items():
            if col_name != "close" and col_name in set():
                if df_wide is not df_base:
                    df_exec_base = df_exec_base.join(df_wide.select(pl.all().exclude(DEFAULT_DATETIME_COL)), on=DEFAULT_DATETIME_COL, how="left")

        # Execute all expressions at once
        result_df = df_exec_base.select(pl.col(DEFAULT_DATETIME_COL), *expressions_to_run)
        return result_df

